### ISSUE TITLE
Stereo OPL2/OPL3 playback using two SD-1 modules

### ISSUE THREAD

**Issue by denjhang** [danielrfry/opl2sd1#2]
I've found that many OPL3 tracks have stereo, whereas the SD-1 is mono. So use two SD-1 combinations to achieve stereo.

**Comment by danielrfry** [comment]
A few people have asked about this so I'm going to try.

One potential issue is that the YMF825Board has the clock oscillator integrated. My suspicion was that the two chips running with independent clocks may produce audio signals that are out-of-phase and create unintentional stereo separation where there should be none.

As a first test, I've connected both YMF825s to the same SPI bus, sharing the same CS and RST lines, so that in theory they receive the same signals simultaneously. I recorded a sample of music playback and subtracted one channel from another in Audacity, which should result in silence if the two chips are producing the same output; however, the tracks do indeed differ in phase and some higher frequencies are still audible in the combined channels. (Those sounds are also audibly separated when listening to the unmodified output).

It's possible that running the two chips from the same clock source would solve that, however I don't have the equipment or skills necessary to remove the YMF825 from the board, nor do I have a source of bare YMF825 chips to build into a new circuit.

It's an interesting experiment nonetheless so I will try updating the code to produce stereo output, and maybe someone with the capability and resources to build a dual-YMF825 circuit can make use of it.

**Comment by denjhang** [comment]
I am capable of building dual YMF825 modules, I will draw the schematic, PCB and solder, I also have some YMF825 chips enough for testing. I can assist you with hardware testing.

**Comment by denjhang** [comment]
In-phase clocks don't seem to solve this problem. Because it is rumored that the initial phase of Yamaha FM is random.

**Comment by denjhang** [comment]
If you can provide interesting OPL3 VGM files like EndlessBreak, I'd like to hear that too.

**Comment by danielrfry** [comment]
Yes, it's still an interesting experiment even if it's not possible to synchronise the two YMF825s perfectly.

I've pushed the stereo code, the builds are here: https://github.com/danielrfry/opl2sd1/actions/runs/4736826783
There are now two firmware images, one for mono and one for stereo operation.

If you'd like to try it, connect both YMF825 modules to the same SPI bus, with pin 6 → left channel YMF825 CS, pin 7 → right channel YMF825 CS.

(Please note I've changed the default pin assignments, so pin 6 is now used instead of pin 1 for CS in the mono firmware too. This is so that I can use pins 0 and 1 for debugging via UART. The documentation is not yet updated).

Endless Break by Pigu is on [Battle of the Bits](https://battleofthebits.org/arena/Entry/Endless+Break+%28short+ver.%29/30542/)!

**Comment by danielrfry** [comment]
I think there may still be bugs in the channel allocator, so it might be possible to improve the performance further on 1 or 2 chips. I'd like to work some more on that when I have more time (I just needed a break from it for a little while!)

But if you'd like to build the 4 chip device anyway, I'd certainly like to see it and will be happy to update the code to support that. We can continue the discussion of that over on issue #7. Thanks!
